version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    links:
      - frontend
  frontend:
    container_name: frontend
    restart: always
    image: fr4nca/frontend
    expose:
      - "3000"
  backend:
    container_name: backend
    restart: always
    image: fr4nca/apieo
    expose:
      - "5000"
