export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_CURRENT_PROFILE = "SET_CURRENT_PROFILE";

export const GET_GAMES = "GET_GAMES";
export const GET_GAME = "GET_GAME";
export const CREATE_GAME = "CREATE_GAME";
export const GET_RANKING = "GET_RANKING";
export const GET_GAMES_ATIVOS = "GET_GAMES_ATIVOS";

export const GET_DISCIPLINAS = "GET_DISCIPLINAS";
export const CREATE_DISCIPLINA = "CREATE_DISCIPLINA";
export const DELETE_DISCIPLINA_PROFESSOR = "DELETE_DISCIPLINA_PROFESSOR";
export const GET_DISCIPLINAS_PROFESSOR = "GET_DISCIPLINAS_PROFESSOR";
export const VINCULATE_DISCIPLINA_PROFESSOR = "VINCULATE_DISCIPLINA_PROFESSOR";

export const GET_TAREFAS = "GET_TAREFAS";
export const GET_TAREFAS_PENDENTES = "GET_TAREFAS_PENDENTES";
export const DELETE_TAREFA = "DELETE_TAREFA";
export const ADD_TAREFA = "ADD_TAREFA";
export const VALIDAR_TAREFA = "VALIDAR_TAREFA";
export const DELETE_ALUNO_TAREFAS = "DELETE_ALUNO_TAREFAS";

export const GET_REGRAS = "GET_REGRAS";
export const ADD_REGRA = "ADD_REGRA";
export const DELETE_REGRA = "DELETE_REGRA";
export const EDIT_REGRA = "EDIT_REGRA";

export const ADD_ALUNO = "ADD_ALUNO";
export const DELETE_ALUNO = "DELETE_ALUNO";
export const GET_ALUNOS = "GET_ALUNOS";
export const GET_ALL_ALUNOS = "GET_ALL_ALUNOS";

export const GET_ERRORS = "GET_ERRORS";

export const GET_MESSAGES = "GET_MESSAGES";
export const CREATE_MESSAGE = "CREATE_MESSAGE";

<<<<<<< HEAD
export const EDIT_PROFILE = "EDIT_PROFILE"
=======
export const RELATORIO_PROFESSOR = "RELATORIO_PROFESSOR";
>>>>>>> 474b09c46ce4b100675c45721337e41122592d01
