export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_CURRENT_PROFILE = "SET_CURRENT_PROFILE";

export const GET_GAMES = "GET_GAMES";
export const GET_GAME = "GET_GAME";
export const CREATE_GAME = "CREATE_GAME";

export const GET_DISCIPLINAS = "GET_DISCIPLINAS";
export const CREATE_DISCIPLINA = "CREATE_DISCIPLINA";
export const GET_DISCIPLINAS_PROFESSOR = "GET_DISCIPLINAS_PROFESSOR";
export const VINCULATE_DISCIPLINA_PROFESSOR = "VINCULATE_DISCIPLINA_PROFESSOR";

export const GET_TAREFAS = "GET_TAREFAS";

export const GET_REGRAS = "GET_REGRAS";
export const ADD_REGRA = "ADD_REGRA";
export const DELETE_REGRA = "DELETE_REGRA";
export const EDIT_REGRA = "EDIT_REGRA";
